export const ModalContainerTheme = {
  centered: "top-1/2 -translate-y-1/2",
  fullscreen: "h-full w-full p-0 m-0 min-h-full max-h-full",
  hidden: "translate-y-[-3.125rem] opacity-0",
  show: "translate-y-0",
  sizeDefault: "w-full px-2.5",
  wrapper: "pointer-events-none ease-in-out mx-auto",
  animation: "transition-all duration-200",
  wrapperPositionDefault: "relative w-auto",
  bottom: "w-full absolute bottom-0 max-h-[calc(100dvh-3.5rem)]",
  "top-left": "w-full absolute left-0",
  "top-right": "w-full absolute right-0",
  sm: "max-w-[calc(100vw-50%)]",
  md: "max-w-[calc(100vw-40%)]",
  lg: "max-w-[calc(100vw-30%)]",
  xl: "max-w-[calc(100vw-20%)]",
  "2xl": "max-w-[calc(100vw-10%)]",
  "static-dialog": "max-w-80 fold-sm:max-w-[calc(100vw-10%)]",
}
